@echo off
setlocal

:: ============================================================================
:: Ensure the script runs from its own directory
:: ============================================================================
pushd "%~dp0"

:: ============================================================================
:: Check for administrative privileges and self-elevate if necessary
:: ============================================================================
>nul 2>&1 "%SYSTEMROOT%\\system32\\cacls.exe" "%SYSTEMROOT%\\system32\\config\\system"
if '%errorlevel%' NEQ '0' (
    echo [INFO] Requesting administrative privileges for firewall setup...
    echo.
    powershell -command "Start-Process -FilePath '%~s0' -Verb RunAs"
    exit /b
)

echo ==============================================
echo      WAIEDU Complete Development Environment
echo ==============================================
echo.

REM --- STEP 1: System Preparation ---
echo [STEP 1] System Preparation
echo =============================
echo.

echo [+] Setting up firewall rules...
netsh advfirewall firewall show rule name="WAIEDU Dev Backend" >nul
if errorlevel 1 (
    netsh advfirewall firewall add rule name="WAIEDU Dev Backend" dir=in action=allow protocol=TCP localport=3000
    echo    - Rule for Port 3000 created.
) else (
    echo    - Rule for Port 3000 already exists.
)

netsh advfirewall firewall show rule name="WAIEDU Dev Staff" >nul
if errorlevel 1 (
    netsh advfirewall firewall add rule name="WAIEDU Dev Staff" dir=in action=allow protocol=TCP localport=3001
    echo    - Rule for Port 3001 created.
) else (
    echo    - Rule for Port 3001 already exists.
)

netsh advfirewall firewall show rule name="WAIEDU Dev Client" >nul
if errorlevel 1 (
    netsh advfirewall firewall add rule name="WAIEDU Dev Client" dir=in action=allow protocol=TCP localport=3002
    echo    - Rule for Port 3002 created.
) else (
    echo    - Rule for Port 3002 already exists.
)
echo    Firewall configured.
echo.

echo [+] Checking port availability...
for %%p in (3000 3001 3002) do (
    netstat -ano | findstr ":%%p" >nul
    if not errorlevel 1 (
        echo [ERROR] Port %%p is already in use. Please stop the existing service using stop-dev.bat.
        goto :eof
    )
)
echo    All required ports are available.
echo.

echo [+] Creating environment file for backend...
(
    echo # WAIEDU Backend Environment Variables
    echo # Auto-generated by start-dev.bat
    echo.
    echo # Server Configuration (0.0.0.0 for public sharing)
    echo PORT=3000
    echo HOST=0.0.0.0
    echo NODE_ENV=development
    echo.
    echo # JWT Configuration
    echo JWT_SECRET=waiedu-secret-key-dev-bat
    echo.
    echo # CORS Configuration (allow all for development)
    echo CORS_ORIGIN=*
) > waiedu_backend\\.env
echo    .env file created.
echo.

REM --- Create logs directory ---
if not exist logs mkdir logs

REM --- STEP 2: Backend Setup (Local) ---
echo [STEP 2] Backend Setup (Local)
echo =================================
echo.
pushd waiedu_backend
if not exist "node_modules" (
    echo [+] Installing backend dependencies with Yarn...
    call yarn
)
echo [+] Starting backend server on port 3000...
start "WAIEDU Backend" /B call yarn start:dev > ..\\logs\\backend.log 2>&1
popd
echo.

REM --- STEP 3: Frontend Setup (Yarn) ---
echo [STEP 3] Frontend Setup (Yarn)
echo =================================
echo.

REM --- Start Staff Frontend ---
pushd waiedu_staff
if not exist "node_modules" (
    echo [+] Installing staff frontend dependencies with Yarn...
    call yarn
)
echo [+] Starting staff frontend server on port 3001...
start "WAIEDU Staff" /B call yarn dev > ..\\logs\\frontend-staff.log 2>&1
popd
echo.

REM --- Start Client Frontend ---
pushd client_staff
if not exist "node_modules" (
    echo [+] Installing client frontend dependencies with Yarn...
    call yarn
)
echo [+] Starting client frontend server on port 3002...
start "WAIEDU Client" /B call yarn dev > ..\\logs\\frontend-client.log 2>&1
popd
echo.

echo [+] Waiting for services to start...
timeout /t 8 >nul

REM --- STEP 4: Server Information & Sharing ---
echo [STEP 4] Server Information
echo ============================
echo.
echo [-] Local Access:
    echo     Backend:      http://localhost:3000
    echo     Staff App:    http://localhost:3001
    echo     Client App:   http://localhost:3002
    echo     Swagger API:  http://localhost:3000/api-docs
echo.
echo [-] Management Commands:
    echo     View backend logs:       powershell -command "Get-Content -Path .\\logs\\backend.log -Wait"
    echo     View staff frontend:     powershell -command "Get-Content -Path .\\logs\\frontend-staff.log -Wait"
    echo     View client frontend:    powershell -command "Get-Content -Path .\\logs\\frontend-client.log -Wait"
    echo     Stop all services:       .\\stop-dev.bat
echo.
echo ========================================
echo   WAIEDU Development Environment Ready!
echo ========================================
echo.

popd
endlocal 